{
	"version": 1645731604,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/fond-sheet0.png",
		"images/errorcount-sheet0.png",
		"images/display-sheet0.png",
		"images/display-sheet1.png",
		"images/display-sheet2.png",
		"images/touche0-sheet0.png",
		"images/touche0-sheet1.png",
		"images/touche1-sheet0.png",
		"images/touche1-sheet1.png",
		"images/touche3-sheet0.png",
		"images/touche3-sheet1.png",
		"images/touche4-sheet0.png",
		"images/touche4-sheet1.png",
		"images/touche5-sheet0.png",
		"images/touche5-sheet1.png",
		"images/touche6-sheet0.png",
		"images/touche6-sheet1.png",
		"images/touche2-sheet0.png",
		"images/touche2-sheet1.png",
		"images/touche7-sheet0.png",
		"images/touche7-sheet1.png",
		"images/touche8-sheet0.png",
		"images/touche8-sheet1.png",
		"images/touche9-sheet0.png",
		"images/touche9-sheet1.png",
		"images/touchediez-sheet0.png",
		"images/touchediez-sheet1.png",
		"images/toucheurgence-sheet0.png",
		"images/toucheurgence-sheet1.png",
		"media/call.ogg",
		"media/appelurgence.ogg",
		"media/indisponible.ogg",
		"media/code d'accès invalide.ogg",
		"media/code d'accès valide.ogg",
		"media/warning alarm sound effects.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}